name: 📖 Documentation
description: For questions, improvements and issues relating to documentation
labels: ['Status: Unconfirmed', 'Documentation']
projects: ['folkehelseinstituttet/12']
body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for helping us improve the documentation!

        > [!TIP]
        >  You may choose between writing in English or Norwegian.
        > _Du kan velge mellom å skrive på engelsk eller norsk._

  - type: input
    id: link
    attributes:
      label: URL to the relevant documentation page
      placeholder: https://...

  - type: textarea
    id: description
    attributes:
      label: Description *
      description: How could we improve the documentation? Is something missing, unclear or confusing?
    validations:
      required: true

  - type: textarea
    id: proposed-improvement
    attributes:
      label: Proposed improvement
      description: Your proposed improvement, if you have any, for the specific part you described above

  - type: textarea
    id: additional-information
    attributes:
      label: Additional information

  - type: markdown
    attributes:
      value: |
        By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/folkehelseinstituttet/Fhi.Frontend.Demo/blob/dev/CODE_OF_CONDUCT.md)
